# Example defaults mirroring sample_output_01.json

auto_create_missing_nodes = true
estimate_label_size_from_font = true

[layout_options]
org.eclipse.elk.algorithm = "layered"
org.eclipse.elk.layered.layering.strategy = "NETWORK_SIMPLEX"
org.eclipse.elk.layered.nodePlacement.strategy = "NETWORK_SIMPLEX"
#org.eclipse.elk.layered.considerModelOrder.strategy = "NODES_AND_EDGES"
org.eclipse.elk.portConstraints = "FREE"
org.eclipse.elk.nodeSize.constraints = "MINIMUM_SIZE"
org.eclipse.elk.nodeSize.options = "[DEFAULT_MINIMUM_SIZE,COMPUTE_PADDING,MINIMUM_SIZE_ACCOUNTS_FOR_PADDING]"
org.eclipse.elk.hierarchyHandling = "INCLUDE_CHILDREN"
org.eclipse.elk.aspectRatio = "1.414"
org.eclipse.elk.zoomToFit = true
org.eclipse.elk.direction = "RIGHT"
org.eclipse.elk.padding = "[top=60,left=60,bottom=60,right=60]"
#org.eclipse.elk.spacing.labelPortHorizontal = 3
#org.eclipse.elk.spacing.labelPortVertical = -3.6
org.eclipse.elk.layered.thoroughness = 100
org.eclipse.elk.edgeRouting = "SPLINES"
#org.eclipse.elk.edgeRouting = "POLYLINE"
#org.eclipse.elk.layered.edgeRouting.polyline.slopedEdgeZoneWidth = 14.0


[node_defaults]
type = "default"
width = 60
height = 60
properties.org.eclipse.elk.portConstraints = "FREE"
properties.org.eclipse.elk.portLabels.treatAsGroup = true
properties.org.eclipse.elk.portLabels.placement = "[OUTSIDE,NEXT_TO_PORT_IF_POSSIBLE]"
properties.org.eclipse.elk.nodeLabels.placement = "[OUTSIDE, V_BOTTOM, H_CENTER, H_PRIORITY]"

[node_defaults.label]
text = "Node"
width = 150
height = 16
properties.org.eclipse.elk.font.name = "Arial"
properties.org.eclipse.elk.font.size = 16

[node_defaults.port]
width = 2.0
height = 2.0
#properties.org.eclipse.elk.port.side = "[NORTH,EAST,SOUTH,WEST]"

[node_defaults.port.label]
text = "Port"
width = 0
height = 2
properties.org.eclipse.elk.font.name = "Arial"
properties.org.eclipse.elk.font.size = 4


[subgraph_defaults]
type = "subgraph"
properties.org.eclipse.elk.portConstraints = "FREE"
properties.org.eclipse.elk.portLabels.placement = "[OUTSIDE, NEXT_TO_PORT_IF_POSSIBLE]"
properties.org.eclipse.elk.nodeLabels.placement = "[INSIDE, V_TOP, H_CENTER]"

[subgraph_defaults.label]
text = "Subgraph"
width = 300
height = 20
properties.org.eclipse.elk.font.name = "Arial"
properties.org.eclipse.elk.font.size = 20

[subgraph_defaults.port]
width = 2.0
height = 2.0

[subgraph_defaults.port.label]
text = "Port"
width = 0
height = 2
properties.org.eclipse.elk.font.name = "Arial"
properties.org.eclipse.elk.font.size = 4

[edge_defaults]
properties.org.eclipse.elk.edge.type = "UNDIRECTED"
properties.org.eclipse.elk.edge.thickness = 1

[edge_defaults.label]
text = "Edge"
width = 200
height = 10
properties.org.eclipse.elk.font.name = "Arial"
properties.org.eclipse.elk.font.size = 10
properties.org.eclipse.elk.edgeLabels.inline = true

#[edge_type_overrides."100g"]
#properties.org.eclipse.elk.edge.type = "UNDIRECTED"
#properties.org.eclipse.elk.edge.thickness = 3

#[edge_type_overrides."100g".label]
#text = "100G"
#width = 140
#height = 12
#properties.org.eclipse.elk.font.size = 11
#properties.org.eclipse.elk.edgeLabels.inline = false

[type_icon_map]
router = "mdi:router"
switch = "clarity:network-switch-line"
mpls = "mdi:cloud-braces"
vpn = "material-symbols:cloud-lock-outline"
firewall = "clarity:firewall-line"
cloud = "material-symbols:cloud-outline"
datacenter = "material-symbols:data-table-outline"
azure = "codicon:azure"
internet = "mdi:web"
cpe = "material-symbols:router-outline"
database = "mdi:database-outline"
server = "mdi:server-outline"
host = "clarity:host-line"
ran = "mdi:radio-tower"
radio = "material-symbols:cell-tower"
splitter = "mdi:axis-arrow"
devices = "mdi:devices"
satelliteuplink = "mdi:satellite-uplink"
satellite = "mdi:satellite-variant"
broadcast = "mdi:cast-audio-variant"
lan = "mdi:lan"
diagnostics = "mdi:bug-outline"
analytics = "mdi:chart-line"
monitor = "mdi:monitor-dashboard"
logging = "mdi:book-edit-outline"
iam = "material-symbols:identity-platform-outline"
idea = "mdi:lightbulb-on-outline"
tools = "mdi:tools"
cctv = "mdi:cctv"
process = "mdi:cog-refresh-outline"
cooling = "mdi:fan"
security = "mdi:lock-outline"
console = "mdi:remote-desktop"
gis = "mdi:map-marker-outline"
city = "mdi:home-city-outline"
settlement = "mdi:home-group"
sdu = "mdi:home-outline"
mdu = "mdi:office-building-outline"
company = "mdi:domain"
farm = "mdi:farm-home-outline"
airport = "mdi:airplane"
mine = "mdi:hammer"
fieldservice = "mdi:briefcase-variant-outline"
facility = "mdi:garage-variant-lock"
energy = "mdi:battery-50"
transmission = "material-symbols:graph-3"
ip = "streamline:cloud-share"
mobilecore = "mdi:mobile-phone-settings-variant"
access = "mdi:connection"
operation = "mdi:account-cog-outline"
controller = "mdi:account-tie-hat-outline"
product = "mdi:cart-outline"
consumer = "mdi:account-outline"
fortinet = "simple-icons:fortinet"
juniper = "simple-icons:junipernetworks"
ericsson = "simple-icons:ericsson"
huawei = "simple-icons:huawei"
cisco = "simple-icons:cisco"
mikrotik = "simple-icons:mikrotik"
dell = "simple-icons:dell"
ubiquiti = "simple-icons:ubiquiti"
